"""agent_subject_space_policy

Revision ID: 4bbdda4f45e5
Revises: b954958cfe04
Create Date: 2026-09-21 12:41:19.109593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bbdda4f45e5"
down_revision: Union[str, Sequence[str], None] = "b954958cfe04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    op.create_index(op.f("ix_agents_tenant_id"), "agents", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_spaces",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sync_state", sa.String(length=16), nullable=False),
        sa.CheckConstraint("sync_state in ('pending','ready','failed')", name="space_sync_state"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    op.create_index(op.f("ix_knowledge_spaces_tenant_id"), "knowledge_spaces", ["tenant_id"], unique=False)
    op.create_table(
        "agent_credentials",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("revoked_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["agents.tenant_id", "agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "agent_id", "id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_agent_credentials_agent_id"), "agent_credentials", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_credentials_tenant_id"), "agent_credentials", ["tenant_id"], unique=False)
    op.create_table(
        "agent_space_grants",
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("space_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["agents.tenant_id", "agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "space_id"],
            ["knowledge_spaces.tenant_id", "knowledge_spaces.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "space_id", "agent_id"),
    )
    op.create_table(
        "person_space_grants",
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("space_id", sa.String(length=32), nullable=False),
        sa.Column("person_id", sa.String(length=32), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("level in ('editor','viewer')", name="person_space_level"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["memberships.tenant_id", "memberships.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "space_id"],
            ["knowledge_spaces.tenant_id", "knowledge_spaces.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "space_id", "person_id"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["agents.tenant_id", "agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "agent_id", "id"),
    )
    op.create_index(op.f("ix_subjects_agent_id"), "subjects", ["agent_id"], unique=False)
    op.create_index(op.f("ix_subjects_tenant_id"), "subjects", ["tenant_id"], unique=False)
    op.create_table(
        "credential_subjects",
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("credential_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "credential_id"],
            ["agent_credentials.tenant_id", "agent_credentials.agent_id", "agent_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id"],
            ["subjects.tenant_id", "subjects.agent_id", "subjects.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "agent_id", "credential_id", "subject_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credential_subjects")
    op.drop_index(op.f("ix_subjects_tenant_id"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_agent_id"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_table("person_space_grants")
    op.drop_table("agent_space_grants")
    op.drop_index(op.f("ix_agent_credentials_tenant_id"), table_name="agent_credentials")
    op.drop_index(op.f("ix_agent_credentials_agent_id"), table_name="agent_credentials")
    op.drop_table("agent_credentials")
    op.drop_index(op.f("ix_knowledge_spaces_tenant_id"), table_name="knowledge_spaces")
    op.drop_table("knowledge_spaces")
    op.drop_index(op.f("ix_agents_tenant_id"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
