"""durable_extraction_jobs_and_candidates

Revision ID: 7bfd5a3d5fb8
Revises: 9558aa10ae69
Create Date: 2026-09-21 12:53:44.841461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bfd5a3d5fb8"
down_revision: Union[str, Sequence[str], None] = "9558aa10ae69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("credential_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("through_sequence", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_token", sa.String(length=32), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.CheckConstraint("state in ('pending','running','retry','succeeded','failed')", name="job_state"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "credential_id"],
            ["agent_credentials.tenant_id", "agent_credentials.agent_id", "agent_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "session_id"],
            [
                "conversations.tenant_id",
                "conversations.agent_id",
                "conversations.subject_id",
                "conversations.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "through_sequence", "kind"),
        sa.UniqueConstraint("tenant_id", "agent_id", "subject_id", "id"),
    )
    op.create_index(op.f("ix_background_jobs_agent_id"), "background_jobs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_background_jobs_state"), "background_jobs", ["state"], unique=False)
    op.create_index(op.f("ix_background_jobs_tenant_id"), "background_jobs", ["tenant_id"], unique=False)
    op.create_table(
        "commit_receipts",
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "job_id"],
            [
                "background_jobs.tenant_id",
                "background_jobs.agent_id",
                "background_jobs.subject_id",
                "background_jobs.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "session_id"],
            [
                "conversations.tenant_id",
                "conversations.agent_id",
                "conversations.subject_id",
                "conversations.id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "agent_id", "session_id", "idempotency_key"),
    )
    op.create_table(
        "memory_candidates",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=4000), nullable=False),
        sa.Column("source_message_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("status in ('candidate','approved','rejected')", name="candidate_status"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "job_id"],
            [
                "background_jobs.tenant_id",
                "background_jobs.agent_id",
                "background_jobs.subject_id",
                "background_jobs.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "ordinal"),
    )
    op.create_index(op.f("ix_memory_candidates_tenant_id"), "memory_candidates", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_candidates_tenant_id"), table_name="memory_candidates")
    op.drop_table("memory_candidates")
    op.drop_table("commit_receipts")
    op.drop_index(op.f("ix_background_jobs_tenant_id"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_state"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_agent_id"), table_name="background_jobs")
    op.drop_table("background_jobs")
    # ### end Alembic commands ###
