"""personal_context_entries

Revision ID: 7f4198c4b3cb
Revises: da912601af82
Create Date: 2026-09-27 22:16:25.760449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f4198c4b3cb"
down_revision: Union[str, Sequence[str], None] = "da912601af82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "namespace_entries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("space_id", sa.String(length=32), nullable=False),
        sa.Column("person_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("source_message_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.CheckConstraint("kind in ('memories','sessions','skills','peers')", name="namespace_entry_kind"),
        sa.CheckConstraint(
            "status in ('pending','active','disabled','deleted')", name="namespace_entry_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["memberships.tenant_id", "memberships.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "space_id"],
            ["knowledge_spaces.tenant_id", "knowledge_spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "space_id", "person_id", "kind", "created_by", "external_id"),
    )
    op.create_index(op.f("ix_namespace_entries_person_id"), "namespace_entries", ["person_id"], unique=False)
    op.create_index(op.f("ix_namespace_entries_space_id"), "namespace_entries", ["space_id"], unique=False)
    op.create_index(op.f("ix_namespace_entries_tenant_id"), "namespace_entries", ["tenant_id"], unique=False)
    op.create_table(
        "namespace_scope_grants",
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("space_id", sa.String(length=32), nullable=False),
        sa.Column("person_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_write", sa.Boolean(), nullable=False),
        sa.CheckConstraint("kind in ('memories','sessions','skills','peers')", name="namespace_scope_kind"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id"],
            ["agents.tenant_id", "agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "person_id"],
            ["memberships.tenant_id", "memberships.person_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "space_id"],
            ["knowledge_spaces.tenant_id", "knowledge_spaces.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "space_id", "person_id", "agent_id", "kind"),
    )
    op.create_table(
        "namespace_messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["namespace_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "external_id"),
        sa.UniqueConstraint("session_id", "sequence"),
    )
    op.create_index(
        op.f("ix_namespace_messages_session_id"), "namespace_messages", ["session_id"], unique=False
    )
    op.create_table(
        "namespace_revisions",
        sa.Column("entry_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["namespace_entries.id"],
        ),
        sa.PrimaryKeyConstraint("entry_id", "version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("namespace_revisions")
    op.drop_index(op.f("ix_namespace_messages_session_id"), table_name="namespace_messages")
    op.drop_table("namespace_messages")
    op.drop_table("namespace_scope_grants")
    op.drop_index(op.f("ix_namespace_entries_tenant_id"), table_name="namespace_entries")
    op.drop_index(op.f("ix_namespace_entries_space_id"), table_name="namespace_entries")
    op.drop_index(op.f("ix_namespace_entries_person_id"), table_name="namespace_entries")
    op.drop_table("namespace_entries")
    # ### end Alembic commands ###
