"""governed_memory_versions

Revision ID: f69e84eead44
Revises: 7bfd5a3d5fb8
Create Date: 2026-09-21 13:03:30.317850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f69e84eead44"
down_revision: str | Sequence[str] | None = "7bfd5a3d5fb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("memory_candidates", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.create_unique_constraint(
        "uq_candidate_scope", "memory_candidates", ["tenant_id", "agent_id", "subject_id", "id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.CheckConstraint("status in ('pending','active','disabled','deleted')", name="memory_status"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "candidate_id"],
            [
                "memory_candidates.tenant_id",
                "memory_candidates.agent_id",
                "memory_candidates.subject_id",
                "memory_candidates.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id"),
        sa.UniqueConstraint("tenant_id", "agent_id", "subject_id", "id"),
    )
    op.create_index(op.f("ix_memory_records_agent_id"), "memory_records", ["agent_id"], unique=False)
    op.create_index(op.f("ix_memory_records_tenant_id"), "memory_records", ["tenant_id"], unique=False)
    op.create_table(
        "memory_revisions",
        sa.Column("memory_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("content", sa.String(length=4000), nullable=True),
        sa.Column("source_message_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "status in ('pending','active','superseded','disabled','deleted')", name="memory_revision_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "memory_id"],
            [
                "memory_records.tenant_id",
                "memory_records.agent_id",
                "memory_records.subject_id",
                "memory_records.id",
            ],
        ),
        sa.PrimaryKeyConstraint("memory_id", "version"),
        sa.UniqueConstraint("tenant_id", "agent_id", "subject_id", "memory_id", "version"),
    )
    op.create_index(op.f("ix_memory_revisions_tenant_id"), "memory_revisions", ["tenant_id"], unique=False)
    op.create_table(
        "memory_projections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=False),
        sa.Column("memory_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("lease_token", sa.String(length=32), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint("kind in ('upsert','delete')", name="memory_projection_kind"),
        sa.CheckConstraint(
            "state in ('pending','running','retry','succeeded','failed','obsolete')",
            name="memory_projection_state",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "agent_id", "subject_id", "memory_id", "version"],
            [
                "memory_revisions.tenant_id",
                "memory_revisions.agent_id",
                "memory_revisions.subject_id",
                "memory_revisions.memory_id",
                "memory_revisions.version",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("memory_id", "version"),
    )
    op.create_index(
        op.f("ix_memory_projections_memory_id"), "memory_projections", ["memory_id"], unique=False
    )
    op.create_index(op.f("ix_memory_projections_state"), "memory_projections", ["state"], unique=False)
    op.create_index(
        op.f("ix_memory_projections_tenant_id"), "memory_projections", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_index(op.f("ix_memory_projections_tenant_id"), table_name="memory_projections")
    op.drop_index(op.f("ix_memory_projections_state"), table_name="memory_projections")
    op.drop_index(op.f("ix_memory_projections_memory_id"), table_name="memory_projections")
    op.drop_table("memory_projections")
    op.drop_index(op.f("ix_memory_revisions_tenant_id"), table_name="memory_revisions")
    op.drop_table("memory_revisions")
    op.drop_index(op.f("ix_memory_records_tenant_id"), table_name="memory_records")
    op.drop_index(op.f("ix_memory_records_agent_id"), table_name="memory_records")
    op.drop_table("memory_records")
    op.drop_constraint("uq_candidate_scope", "memory_candidates", type_="unique")
    op.drop_column("memory_candidates", "version")
    # ### end Alembic commands ###
